### ISSUE TITLE
SZ2 compatibility and PSNR error control

### ISSUE THREAD

**Issue by Wout12345** [szcompressor/SZ3#1]
I'm currently updating my SZ set-up. Although the SZ3 executable states that it is compatible with SZ2 command line arguments, the following command does not work anymore:
```
../compressors/sz -i ../data/volumes/engine_float32 -z ../tmp/compressed-verify-setup -f -3 128 256 256 -M PSNR -S 60
```
It seems like the last part `-M PSNR -S 60` makes the command invalid now. Looking through the SZ3 code for a bit, it seems as if there is no support for PSNR-based error control anymore (or equivalent measures, such as RMSE or relative error). Is this intended or is this work-in-progress?

**Comment by ayzk** [comment]
@Wout12345 Thanks for your interest in SZ3.  Currently, SZ3 doesn't support PSNR bound mode. Further research is needed for this task since the compression algorithm is different. I updated the readme with a list containing all parameters that are not supported by SZ3 as well as the development plan.

**Comment by Wout12345** [comment]
That's good to know, thank you for the quick response!

**Comment by ayzk** [comment]
@Wout12345 V3.1.3 is released with preliminary PSNR-based error control. 
Currently, the gap between the target PSNR and the output PSNR in SZ3 is larger than the gap in SZ2.  Further research to improve the PSNR precision will be on the roadmap.
